### ISSUE TITLE
Subir los cambios que muestren un crud ejecutable

### ISSUE THREAD

**Issue by AndreaLlavel** [CodeSystem2022/ProyectoIntegradorFinal3_EncryptedCode#6]

**Comment by robertoperez2793** [comment]
Codigo optimizado y subido como LaGui_optimizada, en el mismo archivo se integra la ejecucion del codigo y los graficos.

**Comment by AndreaLlavel** [comment]
Recibido

**Comment by AndreaLlavel** [comment]
Me tira error en la linea 106 y 203.
